-- Hand-authored migration intent for review purposes. The actual SQL is
-- generated by `prisma migrate dev`, but the shape is the same.
--
-- Source-table indexes added on top of the original schema:
--   * Outlet (merchantId, isActive)
--   * Merchant (status, category)
--   * CashbackConfiguration (merchantId, isActive, deletedAt)
--   * CashbackConfiguration (startDate, endDate)
--   * CashbackConfigurationTier (cashbackConfigurationId, isActive, deletedAt)
--   * ExclusiveOffer (merchantId, isActive)
--   * ExclusiveOffer (startDate, endDate)
--   * ExclusiveOfferFeedTimeline (customerTypeId)
--   * ExclusiveOfferFeedTimeline (exclusiveOfferId)
--   * LoyaltyTier (loyaltyProgramId, isActive, deletedAt)
--   * CustomerType (userId)
--
-- New table:
CREATE TYPE "OfferIndexType" AS ENUM ('CASHBACK', 'EXCLUSIVE', 'LOYALTY');

CREATE TABLE "OfferIndex" (
  "id"                    TEXT PRIMARY KEY,
  "outletId"              TEXT NOT NULL REFERENCES "Outlet"("id") ON DELETE CASCADE,
  "merchantId"            TEXT NOT NULL,
  "offerType"             "OfferIndexType" NOT NULL,
  "offerId"               TEXT NOT NULL,
  "audience"              TEXT NOT NULL,
  "isAvailable"           BOOLEAN NOT NULL,
  "startDate"             TIMESTAMP(3),
  "endDate"               TIMESTAMP(3),
  "maxCashbackPercentage" DECIMAL(65,30),
  "updatedAt"             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Uniqueness so the builder's "delete-then-createMany" cycle is idempotent.
CREATE UNIQUE INDEX "OfferIndex_outlet_offer_audience_uniq"
  ON "OfferIndex"("outletId", "offerType", "offerId", "audience");

-- Primary read path: resolver's IN(...) over audiences, filtered by isAvailable,
-- aggregating distinct outletId. Putting `audience` first lets us probe each
-- token the user qualifies for.
CREATE INDEX "OfferIndex_audience_available_outlet_idx"
  ON "OfferIndex"("audience", "isAvailable", "outletId");

-- Secondary path for the percentage filter (cashback only) and for any
-- merchant-scoped admin queries.
CREATE INDEX "OfferIndex_merchant_type_available_idx"
  ON "OfferIndex"("merchantId", "offerType", "isAvailable");

-- For the cron sweep that flips rows around date boundaries.
CREATE INDEX "OfferIndex_endDate_available_idx" ON "OfferIndex"("endDate", "isAvailable");
CREATE INDEX "OfferIndex_startDate_available_idx" ON "OfferIndex"("startDate", "isAvailable");

-- Optional: a partial index limited to isAvailable=true rows is even better in
-- production. Postgres can compute this from the composite indexes above, but
-- a partial index halves the size for hot-path scans:
-- CREATE INDEX "OfferIndex_avail_partial"
--   ON "OfferIndex"("audience", "outletId")
--   WHERE "isAvailable" = TRUE;
